image: docker
stages:
  - build_source
  - build_image
  - deploy

variables:
  #CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: codenetix/laravel-dms-frontend:$CI_BUILD_REF_NAME

build_source:
  image: node:9
  stage: build_source
  artifacts:
    untracked: true
    expire_in: 1 day
    paths:
      - dist/
  script:
    - npm install
    - npm run build
  only:
    - dev
  tags:
    - docker-build

build_image:
  stage: build_image
  dependencies:
    - build_source
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    - dev
  tags:
    - docker-build

deploy_dev:
  image: codenetix/kubectl
  variables:
    GIT_STRATEGY: none
  stage: deploy
  only:
    - dev
  script:
    - kubectl set env deploy/dms-frontend-deployment DEPLOY_DATE="$(date)" -n dms-dev
  tags:
    - docker-build
