version: '3'

services:
  frontend_app:
    image: codenetix/laravel-dms-frontend:dev
    container_name: dms_frontend_app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - frontend

networks:
  frontend:
    driver: bridge