version: '3'

services:
  frontend-app:
    image: codenetix/laravel-dms-frontend:dev
    container_name: dms-frontend-app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - frontend

networks:
  frontend:
    driver: bridge